spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/urlshortener}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:redispass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

url-shortener:
  api-path: /api/url/short
  short-url-length: 6
  cache-ttl-minutes: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches
  endpoint:
    caches:
      enabled: true